import { storage, STORAGE_KEYS } from './storage';
import { generateId } from '../utils/id';
import type { Cliente, EventoAgenda, Proposta, RegistroHistorico } from '../types';
import { TAXAS_PADRAO } from './simuladorService';

const SEED_FLAG = 'zaz_crm_seeded';

function diasAtras(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export function seedIfEmpty(): void {
  if (storage.get<boolean>(SEED_FLAG, false)) return;

  const clientes: Cliente[] = [
    {
      id: generateId('cli'),
      nomeFantasia: 'Mercado Bom Preço',
      razaoSocial: 'Bom Preço Comércio de Alimentos Ltda',
      cnpj: '12.345.678/0001-90',
      telefone: '(51) 99999-1234',
      whatsapp: '(51) 99999-1234',
      email: 'contato@mercadobompreco.com.br',
      cidade: 'Osório',
      estado: 'RS',
      endereco: 'Av. Central, 450',
      segmento: 'Supermercado',
      status: 'em_contato',
      responsavel: 'Patrick Lima',
      observacoes: 'Interessado em voucher alimentação para colaboradores.',
      faturamentoEstimado: 200000,
      ticketMedio: 120,
      dataCadastro: diasAtras(9),
    },
    {
      id: generateId('cli'),
      nomeFantasia: 'Restaurante Sabor Caseiro',
      razaoSocial: 'Sabor Caseiro Refeições Ltda',
      cnpj: '23.456.789/0001-11',
      telefone: '(51) 99888-2345',
      whatsapp: '(51) 99888-2345',
      email: 'contato@saborcaseiro.com.br',
      cidade: 'Capão da Canoa',
      estado: 'RS',
      endereco: 'Rua das Flores, 120',
      segmento: 'Restaurante',
      status: 'proposta_enviada',
      responsavel: 'Patrick Lima',
      observacoes: 'Aguardando retorno sobre taxas de cartão.',
      faturamentoEstimado: 85000,
      ticketMedio: 65,
      dataCadastro: diasAtras(4),
    },
    {
      id: generateId('cli'),
      nomeFantasia: 'Agropecuária Campo Verde',
      razaoSocial: 'Campo Verde Agropecuária Ltda',
      cnpj: '34.567.890/0001-22',
      telefone: '(51) 99777-3456',
      whatsapp: '(51) 99777-3456',
      email: 'contato@campoverde.com.br',
      cidade: 'Gravataí',
      estado: 'RS',
      endereco: 'Estrada Rural, km 8',
      segmento: 'Agropecuária',
      status: 'negociacao',
      responsavel: 'Patrick Lima',
      observacoes: 'Reunião marcada para apresentar Banricompras.',
      faturamentoEstimado: 310000,
      ticketMedio: 450,
      dataCadastro: diasAtras(6),
    },
    {
      id: generateId('cli'),
      nomeFantasia: 'Padaria Pão Quente',
      razaoSocial: 'Pão Quente Panificadora Ltda',
      cnpj: '45.678.901/0001-33',
      telefone: '(51) 99666-4567',
      whatsapp: '(51) 99666-4567',
      email: 'contato@paoquente.com.br',
      cidade: 'Tramandaí',
      estado: 'RS',
      endereco: 'Av. Beira Mar, 780',
      segmento: 'Padaria',
      status: 'novo_lead',
      responsavel: 'Patrick Lima',
      observacoes: 'Novo lead recebido via indicação.',
      faturamentoEstimado: 60000,
      ticketMedio: 35,
      dataCadastro: diasAtras(4),
    },
    {
      id: generateId('cli'),
      nomeFantasia: 'Loja Estilo & Cia',
      razaoSocial: 'Estilo & Cia Confecções Ltda',
      cnpj: '56.789.012/0001-44',
      telefone: '(51) 99555-5678',
      whatsapp: '(51) 99555-5678',
      email: 'contato@estiloecia.com.br',
      cidade: 'Tramandaí',
      estado: 'RS',
      endereco: 'Rua do Comércio, 300',
      segmento: 'Vestuário',
      status: 'fechado',
      responsavel: 'Patrick Lima',
      observacoes: 'Fechado com plano de antecipação semanal.',
      faturamentoEstimado: 95000,
      ticketMedio: 140,
      dataCadastro: diasAtras(5),
    },
    {
      id: generateId('cli'),
      nomeFantasia: 'Mercado Econômico',
      razaoSocial: 'Econômico Distribuidora Ltda',
      cnpj: '67.890.123/0001-55',
      telefone: '(51) 99444-6789',
      whatsapp: '(51) 99444-6789',
      email: 'contato@mercadoeconomico.com.br',
      cidade: 'Osório',
      estado: 'RS',
      endereco: 'Rua Nova, 55',
      segmento: 'Supermercado',
      status: 'novo_lead',
      responsavel: 'Patrick Lima',
      observacoes: '',
      faturamentoEstimado: 70000,
      ticketMedio: 90,
      dataCadastro: diasAtras(3),
    },
    {
      id: generateId('cli'),
      nomeFantasia: 'Distribuidora Sul',
      razaoSocial: 'Sul Distribuição de Alimentos Ltda',
      cnpj: '78.901.234/0001-66',
      telefone: '(51) 99333-7890',
      whatsapp: '(51) 99333-7890',
      email: 'contato@distribuidorasul.com.br',
      cidade: 'Cidreira',
      estado: 'RS',
      endereco: 'Av. Industrial, 220',
      segmento: 'Distribuidora',
      status: 'em_contato',
      responsavel: 'Patrick Lima',
      observacoes: '',
      faturamentoEstimado: 420000,
      ticketMedio: 800,
      dataCadastro: diasAtras(3),
    },
    {
      id: generateId('cli'),
      nomeFantasia: 'Restaurante Prato Cheio',
      razaoSocial: 'Prato Cheio Alimentação Ltda',
      cnpj: '89.012.345/0001-77',
      telefone: '(51) 99222-8901',
      whatsapp: '(51) 99222-8901',
      email: 'contato@pratocheio.com.br',
      cidade: 'Capão da Canoa',
      estado: 'RS',
      endereco: 'Rua Litorânea, 90',
      segmento: 'Restaurante',
      status: 'proposta_enviada',
      responsavel: 'Patrick Lima',
      observacoes: '',
      faturamentoEstimado: 78000,
      ticketMedio: 55,
      dataCadastro: diasAtras(4),
    },
  ];

  storage.save(STORAGE_KEYS.clientes, clientes);

  const hoje = new Date().toISOString().slice(0, 10);
  const eventos: EventoAgenda[] = [
    {
      id: generateId('evt'),
      clienteId: clientes[0].id,
      clienteNome: clientes[0].nomeFantasia,
      tipo: 'visita',
      data: hoje,
      hora: '09:00',
      status: 'concluido',
      observacoes: 'Conversamos com o responsável sobre as soluções da ZAZ.',
    },
    {
      id: generateId('evt'),
      clienteId: clientes[1].id,
      clienteNome: clientes[1].nomeFantasia,
      tipo: 'ligacao',
      data: hoje,
      hora: '11:00',
      status: 'pendente',
    },
    {
      id: generateId('evt'),
      clienteId: clientes[2].id,
      clienteNome: clientes[2].nomeFantasia,
      tipo: 'reuniao',
      data: hoje,
      hora: '14:00',
      status: 'pendente',
    },
    {
      id: generateId('evt'),
      clienteId: clientes[3].id,
      clienteNome: clientes[3].nomeFantasia,
      tipo: 'proposta',
      data: hoje,
      hora: '16:30',
      status: 'pendente',
    },
    {
      id: generateId('evt'),
      clienteId: clientes[4].id,
      clienteNome: clientes[4].nomeFantasia,
      tipo: 'retorno',
      data: hoje,
      hora: '10:00',
      status: 'pendente',
      observacoes: 'Retornar proposta',
    },
    {
      id: generateId('evt'),
      clienteId: clientes[5].id,
      clienteNome: clientes[5].nomeFantasia,
      tipo: 'retorno',
      data: hoje,
      hora: '10:30',
      status: 'pendente',
      observacoes: 'Aguardar decisão',
    },
    {
      id: generateId('evt'),
      clienteId: clientes[6].id,
      clienteNome: clientes[6].nomeFantasia,
      tipo: 'retorno',
      data: hoje,
      hora: '11:30',
      status: 'pendente',
      observacoes: 'Confirmar interesse',
    },
  ];
  storage.save(STORAGE_KEYS.agenda, eventos);

  const propostas: Proposta[] = [
    {
      id: generateId('prop'),
      clienteId: clientes[1].id,
      clienteNome: clientes[1].nomeFantasia,
      valor: 8500,
      parcelamento: 1,
      taxas: TAXAS_PADRAO,
      data: diasAtras(2),
      status: 'enviada',
    },
    {
      id: generateId('prop'),
      clienteId: clientes[7].id,
      clienteNome: clientes[7].nomeFantasia,
      valor: 5200,
      parcelamento: 3,
      taxas: TAXAS_PADRAO,
      data: diasAtras(1),
      status: 'enviada',
    },
    {
      id: generateId('prop'),
      clienteId: clientes[4].id,
      clienteNome: clientes[4].nomeFantasia,
      valor: 12000,
      parcelamento: 6,
      taxas: TAXAS_PADRAO,
      data: diasAtras(5),
      status: 'aceita',
    },
  ];
  storage.save(STORAGE_KEYS.propostas, propostas);

  const historico: RegistroHistorico[] = [
    {
      id: generateId('hist'),
      clienteId: clientes[0].id,
      clienteNome: clientes[0].nomeFantasia,
      tipo: 'visita',
      titulo: 'Visita realizada',
      descricao: 'Conversamos com o responsável sobre as soluções da ZAZ.',
      data: diasAtras(0),
    },
    {
      id: generateId('hist'),
      clienteId: clientes[0].id,
      clienteNome: clientes[0].nomeFantasia,
      tipo: 'proposta',
      titulo: 'Enviou proposta',
      descricao: 'Proposta de voucher alimentação enviada por e-mail.',
      data: diasAtras(1),
    },
    {
      id: generateId('hist'),
      clienteId: clientes[0].id,
      clienteNome: clientes[0].nomeFantasia,
      tipo: 'cadastro',
      titulo: 'Primeiro contato',
      descricao: 'Ligação inicial para apresentação dos benefícios.',
      data: diasAtras(2),
    },
  ];
  storage.save(STORAGE_KEYS.historico, historico);

  storage.save(SEED_FLAG, true);
}
